
version: 2

models:
  - name: dates
    description: ""
    columns:
      - name: d_date_sk
        tests:
          - unique
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          - dbt_expectations.expect_column_values_to_have_consistent_casing:
              display_inconsistent_columns: false # (Optional) 
      - name: d_weekend
        tests:
          - accepted_values:
              values: ['Y','N']
